### ISSUE TITLE
Ortalama sorunu.

### ISSUE THREAD

**Issue by kodbilenadam** [data-deveb/data-deveb.github.io#8]
Selamlar,

Takım sayfasına girdiğim zaman bazı font-awesome ikonlarının sol tarafa doğru yaslandığını gördüm ve bunun üzerine Geliştirici Araçlarında biraz test yaptım ve sanırım `data-ort` class'ının istendiği gibi çalışmadığını gördüm. 

Normalde tüm yazılar ve ikonların ortalanması gerekiyorken belirli bir karakter sınırına kadar ortalanmıyorlar. 

İyi çalışmalar.

![Örnek](https://user-images.githubusercontent.com/7461799/32495960-b6313b34-c3d8-11e7-95a1-b9aab14b85e6.png)

**Comment by volkantash** [comment]
Selam. Resimdeki sonuca sebep olan kaynak kodlarını paylaşabilir misiniz? Teşekkürler.
